{{- if .Values.customServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "plugin-barman-cloud.labels" . | nindent 4 }}
  {{- with .Values.customServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: plugin-barman-cloud
  namespace: {{ .Release.Namespace }}
{{- end }}
