apiVersion: v2
appVersion: 0.7.0
name: plugin-barman-cloud
description: A Helm chart for plugin-barman-cloud
home: https://github.com/giantswarm/plugin-barman-cloud
maintainers:
  - name: giantswarm/team-atlas
    email: team-atlas@giantswarm.io
# If you have an icon/logo, you should add it to https://github.com/giantswarm/web-assets
# and set the final URL as a value here and uncomment.
#icon: https://s.giantswarm.io/app-icons/example/1/light.svg
sources:
- https://github.com/cloudnative-pg/charts/tree/main/charts/plugin-barman-cloud
dependencies:
  - name: plugin-barman-cloud
    alias: pluginbarmancloud
    version: 0.2.0
    repository: https://cloudnative-pg.io/charts
    condition: pluginbarmancloud.enabled
version: 0.0.1
annotations:
  application.giantswarm.io/team: atlas
