apiVersion: v2
appVersion: 0.7.0
name: plugin-barman-cloud
description: A Helm chart for plugin-barman-cloud
home: https://github.com/giantswarm/plugin-barman-cloud
maintainers:
  - name: giantswarm/team-atlas
    email: team-atlas@giantswarm.io
icon: https://s.giantswarm.io/app-icons/cloudnative-pg/icon-light.svg
sources:
  - https://github.com/cloudnative-pg/charts/tree/main/charts/plugin-barman-cloud
dependencies:
  - name: plugin-barman-cloud
    alias: pluginbarmancloud
    version: 0.3.1
    repository: https://cloudnative-pg.io/charts
    condition: pluginbarmancloud.enabled
version: 0.2.2
annotations:
  io.giantswarm.application.team: atlas
